myproject/guestbook/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.author_login, name='login'),
    url(r'^logout/$', views.author_logout, name='logout'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^unique_name/$', views.unique_name, name='unique_name'),
    url(r'^author/(?P<username>[^\s]+)/$', views.author_entries, name='author_entries'),
    url(r'^entry/(?P<entry_pk>[0-9]+)/$', views.view_entry, name='view_entry'),
    url(r'^add-entry/$', views.add_entry, name='add_entry'),
    url(r'^add-comment/(?P<entry_pk>[0-9]+)/$', views.add_comment, name='add_comment'),
    url(r'^$', views.index, name='index'),
]

myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guestbook/', include('guestbook.urls', namespace='guestbook', app_name='guestbook')),
    url(r'^table/', include('table.urls', namespace='table', app_name='table')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index')
]

myproject/table/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^populate-rows/$', views.populate_rows, name='populate_rows'),
    url(r'^purge-table/$', views.purge_table, name='purge_table'),
    url(r'^delete-row/(?P<row_pk>[0-9]+)/$', views.delete_row, name='delete_row'),
    url(r'^add-row/$', views.add_row, name='add_row'),
    url(r'^(?P<row_pk>[0-9]+)/$', views.edit_row, name='edit_row')
]

myproject/guestbook/models.py
from django.db import models
from django.contrib.auth.models import User


class Entry(models.Model):
    content = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('Author')

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return '{}'.format(self.content[:11])


class Comment(models.Model):
    content = models.CharField(max_length=70)
    date = models.DateTimeField(auto_now_add=True)
    entry = models.ForeignKey('Entry')
    author = models.ForeignKey('Author')

    def __str__(self):
        return '{}'.format(self.content[:11])


class Author(models.Model):
    user = models.OneToOneField(User)
    date_registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

myproject/guestbook/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import ModelForm, Textarea, PasswordInput
from .models import Entry, Comment


class LoginForm(forms.Form):
    username = forms.CharField(label='Логин', max_length=20)
    password = forms.CharField(
        label='Пароль', widget=forms.PasswordInput(), max_length=20)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Неправильная пара логин-пароль")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user


class EntryForm(ModelForm):

    class Meta:
        model = Entry
        fields = ('content', )
        labels = {'content': 'Текст записи:'}
        widgets = {
            'content': Textarea(attrs={'cols': 80, 'rows': 10, 'class': 'form-control'})
        }


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('content', )
        labels = {'content': 'Текст комментария:'}
        widgets = {
            'content': Textarea(attrs={'cols': 70, 'rows': 1, 'class': 'form-control'})
        }


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'password': PasswordInput(attrs={})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control', 'style': 'width:25%'})

myproject/guestbook/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect

from .models import Entry, Comment, Author
from .forms import EntryForm, CommentForm, UserForm, LoginForm


def index(request):
    entry_list = Entry.objects.all().order_by('-date')

    paginator = Paginator(entry_list, 5)
    page = request.GET.get('page')
    try:
        entries = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        entries = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        entries = paginator.page(paginator.num_pages)

    return render(request, 'guestbook/index.html', {'entries': entries})


def view_entry(request, entry_pk):
    try:
        entry = Entry.objects.get(pk=entry_pk)
    except ObjectDoesNotExist:
        return HttpResponse('Запись, которую вы пытаетесь просмотреть, не существует')
    comments = entry.comment_set.all()
    return render(request, 'guestbook/entry.html', {'entry': entry, 'comments': comments})


@login_required
def add_entry(request):
    if request.method == 'POST':
        entry_form = EntryForm(request.POST)
        if entry_form.is_valid():
            entry = entry_form.save(commit=False)
            content = entry.content
            author = Author.objects.get(user=request.user)
            Entry.objects.create(content=content, author=author)
            return HttpResponseRedirect(reverse('guestbook:index'))
    else:
        entry_form = EntryForm()
    return render(request, 'guestbook/add-entry.html', {'entry_form': entry_form})


@login_required
def add_comment(request, entry_pk):
    try:
        entry = Entry.objects.get(pk=entry_pk)
    except ObjectDoesNotExist:
        return HttpResponse('Запись, которую вы пытаетесь прокомментировать, не существует')

    entry = Entry.objects.get(pk=entry_pk)
    comments = entry.comment_set.all()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            content = comment.content
            author = Author.objects.get(user=request.user)
            Comment.objects.create(content=content, author=author, entry=entry)
            return HttpResponseRedirect(reverse('guestbook:index'))
    else:
        comment_form = CommentForm()
    return render(request, 'guestbook/add-comment.html', {'comment_form': comment_form, 'entry': entry, 'comments': comments})


def author_entries(request, username):
    user = User.objects.get(username=username)
    author = Author.objects.get(user=user)
    entries = author.entry_set.all()
    return render(request, 'guestbook/author.html', {'entries': entries, 'username': username})


def unique_name(request):
    if request.method == 'GET':
        name = request.GET.get('username', '')
        print(Author.objects.filter(user__username=name).exists())
    return HttpResponse(Author.objects.filter(user__username=name).exists())


def registration(request):
    username = ''

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            username = user.username
            password = user.password
            user = User.objects.create_user(username=username, password=password)
            author = Author(user=user)
            author.save()
            author = authenticate(username=username, password=password)
            login(request, author)
            return HttpResponseRedirect(reverse('guestbook:index'))
    else:
        user_form = UserForm()
    return render(request, 'guestbook/registration.html', {'user_form': user_form, 'username': username})


def author_login(request):
    next = ''
    if request.GET:
        next = request.GET['next']
        print('next is ' + next)

    print("next is " + next)

    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            if next:
                return HttpResponseRedirect(next)
            else:
                return HttpResponseRedirect(reverse('guestbook:index'))
    return render(request, 'guestbook/login.html', {'login_form': form})


@login_required
def author_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('guestbook:index'))

myproject/templates/guestbook/add-comment.html
{% extends 'guestbook/base.html' %}
{% load static %}

{% block title %} Добавить комментарий {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}


	<h3>Добавить комментарий к записи</h3>
	<h4>Текст записи:</h4>
	<p>{{ entry.content }}</p>
	<h4>Автор записи:</h4>
	<p>{{ entry.author }}, {{ entry.date }}</p>
	<h4>Дата записи:</h4>
	<p>{{ entry.date }}</p>

	<h4>Ваш комментарий:</h4>

	<form method="post">

	    {% csrf_token %}

	    {{ comment_form.as_p }}

	    <input type="submit" name="submit" value="Комментировать" class="btn btn-primary btn-xs">
	</form>

	{% if comments %}
	<h4>Комментарии, сделанные ранее:</h4>
	<ul class="list-group">
		{% for comment in comments %}
		<li class="list-group-item">{{ comment.content }}, написал <a href="{% url 'guestbook:author_entries' comment.author %}">{{ comment.author }}</a> {{ comment.date }}</li>
		{% endfor %}
	</ul>
	{% else %}
	<h4>Эту запись пока никто не комментировал до вас</h4>
	{% endif %}

{% endblock %}

myproject/templates/guestbook/add-entry.html
{% extends 'guestbook/base.html' %}
{% load static %}

{% block title %} Добавить запись {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}

	<form method="post">

	    {% csrf_token %}

	    {{ entry_form.as_p }}

	    <input type="submit" name="submit" value="Добавить" class="btn btn-primary btn-xs">
	</form>

{% endblock %}

myproject/templates/guestbook/author.html
{% extends 'guestbook/base.html' %}
{% load static %}

{% block title %}Записи {{ username }}{% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}

	<h3>Записи {{ username }}</h3>

	<ul class="list-group" id="entries">
		{% for entry in entries %}		
		<li class="list-group-item">
 			<div class="entry">
 				<a href="{% url 'guestbook:view_entry' entry.pk %}">
					{{ entry.content|truncatechars:148 }}</a>
			</div>
			<div class="entry-meta">
				<span class="meta-chunk">{{ entry.date }}</span>
				<span class="meta-chunk">Комментариев: <a href="{% url 'guestbook:view_entry' entry.pk %}">{{ entry.comment_set.all|length }}</span>
				<span class="meta-chunk"><a href="{% url 'guestbook:add_comment' entry.pk %}">Комментировать</a></span>
			</div>
		</li>
		{% endfor %}
	</ul>

{% endblock %}

myproject/templates/guestbook/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
    	<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css'  %}">
    <style>{% block styles %}{% endblock %}</style>
	</head>
	<body>

		<div class="container">
			<a href="/">К оглавлению</a>
			<h1 id="upper-header"><a href="{% url 'guestbook:index' %}">Гостевая</a></h1>
			<div id="upper-auth">
				{% if user.is_authenticated %}
				Здравствуйте, <a href="{% url 'guestbook:author_entries' user.username %}">{{ user.username }}</a>
				<a href="{% url 'guestbook:logout' %}">Выйти</a>
				{% else %}
				<a href="{% url 'guestbook:login' %}">Войти</a>
				<a href="{% url 'guestbook:registration' %}"> Регистрация</a>
				{% endif %}
			</div>
			<h4 id="perex">C блэкджеком и комментариями</h4>
			{% block content %}
			{% endblock %}
		</div>

		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<script>{% block scripts %}{% endblock %}</script>
	</body>
</html>

myproject/templates/guestbook/entry.html
{% extends 'guestbook/base.html' %}
{% load static %}

{% block title %} Просмотр комментариев {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}

	<h3>Просмотр комментариев</h3>
	<h4>Текст записи:</h4>
	<p>{{ entry.content }}</p>
	<h4>Автор записи:</h4>
	<p>{{ entry.author }}, {{ entry.date }}</p>
	<h4>Дата записи:</h4>
	<p>{{ entry.date }}</p>

	<a href="{% url 'guestbook:add_comment' entry.pk %}" class="btn btn-primary btn-xs">Прокомментировать</a>

	{% if comments %}
	<h4>Комментарии, сделанные ранее:</h4>
	<ul class="list-group">
		{% for comment in comments %}
		<li class="list-group-item">{{ comment.content }}, написал <a href="{% url 'guestbook:author_entries' comment.author %}">{{ comment.author }}</a> {{ comment.date }}</li>
		{% endfor %}
	</ul>
	{% else %}
	<p><strong>Эту запись пока никто не комментировал</strong></p>
	{% endif %}

{% endblock %}

myproject/templates/guestbook/index.html
{% extends 'guestbook/base.html' %}
{% load static %}

{% block title %} Главная {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}
	<div id="add-entry">
		<a href="{% url 'guestbook:add_entry' %}" class="btn btn-primary btn-xs">Добавить запись</a>
		<a href="http://www.codeskulptor.org/#user40_I7OFTdMzyj_21.py" target="_blank">Блэкджек!</a>
	</div>
	<ul class="list-group" id="entries">
		{% for entry in entries %}		
		<li class="list-group-item">
 			<div class="entry">
 				<a href="{% url 'guestbook:view_entry' entry.pk %}">
					{{ entry.content|truncatechars:148 }}</a>
			</div>
			<div class="entry-meta">
				<span class="meta-chunk">{{ entry.date }}</span>
				<span class="meta-chunk"><a href="{% url 'guestbook:author_entries' entry.author %}">{{ entry.author }}</a></span>
				<span class="meta-chunk">Комментариев: <a href="{% url 'guestbook:view_entry' entry.pk %}">{{ entry.comment_set.all|length }}</span>
				<span class="meta-chunk"><a href="{% url 'guestbook:add_comment' entry.pk %}">Комментировать</a></span>
			</div>
		</li>
		{% endfor %}
	</ul>

	<div class="pagination-container">
		<ul class="pagination pagination-sm">

		{% if entries.paginator.num_pages > 1 %}
		    {% if entries.has_previous %}
		        <li><a href="?page={{ entries.previous_page_number }}">←</a></li>
		    {% endif %}

			{% for num in entries.paginator.page_range %}
		        {% if num == entries.number %}
		            <li><a id="current">{{ num }}</a></li>
		        {% else %}
		            <li><a href="?page={{ num }}"> {{ num }}</a></li>
		        {% endif %} 
		    {% endfor %}

		    {% if entries.has_next %}
		        <li><a href="?page={{ entries.next_page_number }}">→</a></li>
		    {% endif %}

		{% endif %}
		</ul>
	</div>

{% endblock %}

myproject/templates/guestbook/login.html
{% extends 'guestbook/base.html' %}
{% load static %}

{% block title %} Вход {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
	$(function() {
		$('input[type=text]').addClass('form-control');
		$('input[type=password]').addClass('form-control');		
	});
{% endblock %}

{% block content %}

	<h1>Вход</h1>
	
	<form method="post" style="width:25%">
		{% csrf_token %}
		<p class='errorlist'></p>
		{{ login_form.as_p }}

	    <input type="submit" name="submit" value="Войти" class="btn btn-primary btn-xs"><a href="{% url 'guestbook:registration' %}"> Зарегистрироваться</a>
	</form>

{% endblock %}

myproject/templates/guestbook/registration.html
{% extends 'guestbook/base.html' %}
{% load static %}

{% block title %} Регистрация {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
	$(function() {
		$('#id_username').keyup(function(){
	        name = $(this).val();
	        $.get('/unique_name/', {'username': name}, function(data){
	        	if (data == 'True'){
	        		$('.is-taken').html("Имя уже занято");
	        	} else {
	        		$('.is-taken').html("");
	        	}
	        });
		});
	});
{% endblock %}

{% block content %}

	<h1>Регистрация</h1>
	<form method="post">
		{% csrf_token %}
		<p class="is-taken"></p>
	    {{ user_form.as_p }}
	    <input type="submit" name="submit" value="Зарегистрироваться" class="btn btn-primary btn-xs">
	</form>

{% endblock %}