myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guestbook/', include('guestbook.urls', namespace='guestbook', app_name='guestbook')),
    url(r'^table/', include('table.urls', namespace='table', app_name='table')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index')
]

myproject/table/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^populate-rows/$', views.populate_rows, name='populate_rows'),
    url(r'^purge-table/$', views.purge_table, name='purge_table'),
    url(r'^delete-row/(?P<row_pk>[0-9]+)/$', views.delete_row, name='delete_row'),
    url(r'^add-row/$', views.add_row, name='add_row'),
    url(r'^(?P<row_pk>[0-9]+)/$', views.edit_row, name='edit_row')
]

myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
    	<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css'  %}">
    <style>{% block styles %}{% endblock %}</style>
	</head>
	<body>
		<div class="container">
		{% block content %}
		{% endblock %}
		</div>

		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<script>{% block scripts %}{% endblock %}</script>
	</body>
</html>

myproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
    	<title>Список тестовых заданий</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css'  %}">
    <style>{% block styles %}{% endblock %}</style>
	</head>
	<body>

		<div class="container">
			<li><a href="{% url 'guestbook:index' %}">Гостевая</a></li>
			<li><a href="{% url 'table:index' %}">Таблица</a></li>
		</div>

		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<script>{% block scripts %}{% endblock %}</script>
	</body>
</html>