myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guestbook/', include('guestbook.urls', namespace='guestbook', app_name='guestbook')),
    url(r'^table/', include('table.urls', namespace='table', app_name='table')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index')
]

myproject/table/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^populate-rows/$', views.populate_rows, name='populate_rows'),
    url(r'^purge-table/$', views.purge_table, name='purge_table'),
    url(r'^delete-row/(?P<row_pk>[0-9]+)/$', views.delete_row, name='delete_row'),
    url(r'^add-row/$', views.add_row, name='add_row'),
    url(r'^(?P<row_pk>[0-9]+)/$', views.edit_row, name='edit_row')
]

myproject/table/models.py
from django.db import models
import random
import string

from .forms import NUMBER_OF_CELLS, MIN_LETTERS, MAX_LETTERS_FROM, MAX_LETTERS_TO


class Cell(models.Model):
    content = models.CharField(max_length=100, null=True, blank=True)
    row = models.ForeignKey('Row')

    def __str__(self):
        try:
            return '{}'.format(self.content[:10])
        except TypeError:
            return ''


class Row(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    @classmethod
    def create(cls):
        row = cls()
        row.save()
        for i in range(NUMBER_OF_CELLS):
            content = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(MIN_LETTERS, random.randint(MAX_LETTERS_FROM, MAX_LETTERS_TO)))
            cell = Cell.objects.create(content=content, row=row)
        return row

    class Meta:
        ordering = ('-created',)

    # def __str__(self):
    #     return '{}'.format(self.pk)

myproject/table/forms.py
from django import forms
from django.forms.formsets import BaseFormSet

NUMBER_OF_ROWS = 6
NUMBER_OF_CELLS = 5
MIN_LETTERS = 5
MAX_LETTERS_FROM = 10
MAX_LETTERS_TO = 15


class RowForm(forms.Form):
    cell = forms.CharField(label='Ячейка', max_length=100)


class RowFormSet(BaseFormSet):
    min_num = 0
    max_num = NUMBER_OF_CELLS
    absolute_max = NUMBER_OF_CELLS
    extra = NUMBER_OF_CELLS
    form = RowForm
    can_order = False
    can_delete = False
    validate_max = True
    validate_min = True

    def __init__(self, *args, **kwargs):
        super(RowFormSet, self).__init__(*args, **kwargs)
        for i in range(0, NUMBER_OF_CELLS):
            self[i].fields['cell'].label += " %d" % (i + 1)

myproject/table/views.py
from django.urls import reverse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect

from .models import Cell, Row
from .forms import RowFormSet, NUMBER_OF_ROWS


def index(request):
    rows = Row.objects.all()
    return render(request, 'table/index.html', {'rows': rows})


def populate_rows(request):
    if Row.objects.count() == 0:
        for i in range(NUMBER_OF_ROWS):
            row = Row.create()
    return HttpResponseRedirect(reverse('table:index'))


def purge_table(request):
    Row.objects.all().delete()
    return HttpResponseRedirect(reverse('table:index'))


def delete_row(request, row_pk):
    try:
        row = Row.objects.get(pk=row_pk)
    except Row.DoesNotExist:
        return HttpResponse('Такая строка не существует')
    row.delete()
    return HttpResponseRedirect(reverse('table:index'))


def add_row(request):
    if request.method == 'POST':
        formset = RowFormSet(request.POST)
        if formset.is_valid():
            row = Row.objects.create()
            for form in formset:
                cd = form.cleaned_data
                content = cd.get('cell')
                cell = Cell.objects.create(content=content, row=row)
            return HttpResponseRedirect(reverse('table:index'))
    else:
        formset = RowFormSet()

    return render(request, 'table/add-row.html', {'formset': formset})


def edit_row(request, row_pk):
    try:
        row = Row.objects.get(pk=row_pk)
    except Row.DoesNotExist:
        return HttpResponse('Такая строка не существует')

    cells = Cell.objects.filter(row=row)

    contents = []

    if request.method == 'POST':
        formset = RowFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                cd = form.cleaned_data
                content = cd.get('cell')

                contents.append(content)

            for i, cell in enumerate(cells):
                cell.content = contents[i]
                cell.save()
        return HttpResponseRedirect(reverse('table:index'))
    else:
        formset = RowFormSet()

    return render(request, 'table/edit-row.html', {'formset': formset, 'row_pk': row_pk})

myproject/templates/table/add-row.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Добавить строку {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}

	<a href="{% url 'table:index' %}">К таблице</a>

	<form method="post">

	    {% csrf_token %}

	    {{ formset.as_p }}

	    <input type="submit" name="submit" value="Добавить" class="btn btn-primary btn-xs">
	    <button class="btn btn-default btn-xs"><a href="{% url 'table:index' %}">Отмена</a></button>
	</form>

{% endblock %}

myproject/templates/table/edit-row.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Добавить строку {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}
	<a href="{% url 'table:index' %}">К таблице</a>

	<form method="post">

	    {% csrf_token %}

	    {{ formset.as_p }}

	    <input type="submit" name="submit" value="Сохранить" class="btn btn-primary btn-xs">
	    <button class="btn btn-default btn-xs"><a href="{% url 'table:delete_row' row_pk %}">Удалить текущую строку</a></button>
	    <button class="btn btn-default btn-xs"><a href="{% url 'table:index' %}">Отмена</a></button>
	</form>

{% endblock %}

myproject/templates/table/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Главная {% endblock %}

{% block styles %}
{% endblock %}
{% block scripts %}

	$(function() {
		$('a').mouseenter(function(){
		    $(this).parent().siblings().children('a').css('text-decoration', 'underline')
		});
		$('a').mouseleave(function(){
		    $(this).parent().siblings().children('a').css('text-decoration', 'none')
		});
	});

{% endblock %}

{% block content %}
	<a href="/">К оглавлению</a>
	{% if rows.count == 0 %}
		<div>
			<button class="btn btn-default">
				<a href="{% url 'table:populate_rows' %}">Заполнить таблицу</a>
			</button>
		</div>
	{% else %}
		<div>
			<button class="btn btn-default">
				<a href="{% url 'table:add_row' %}">Добавить строку таблицы</a>
			</button>
			<button class="btn btn-default">
				<a href="{% url 'table:purge_table' %}">Очистить таблицу</a>
			</button>
		</div>
	{% endif %}

	<table>
		{% for row in rows %}
			<tr>
				{% for cell in row.cell_set.all %}
					<td><a href="{% url 'table:edit_row' row.pk %}">{{ cell }}</a></td>
				{% endfor %}
			</tr>
		{% endfor %}
	</table>


{% endblock %}